version: '3.7'
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend

  postgres:
    image: postgres:12
    restart: unless-stopped
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  redis:
    image: redis:6.2.7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data:cached 

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python app/main.py
    tty: true
    volumes:
      - .src/backend:/app/:cached
      - .src/.docker/.ipython:/root/.ipython:cached
    env_file: .env
    environment:
      PYTHONPATH: .
    depends_on:
      - "postgres"
      - "redis"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - '.src/frontend:/app:cached'
      - '.src/frontend/node_modules:/app/node_modules:cached'
    environment:
      - NODE_ENV=development

volumes:
  db-data:
  redis:
